apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ .Values.rbac.roleName }}
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list"]
 - apiGroups: [""]
   resources: ["nodes/checkpoint"]
   verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: {{ .Values.rbac.roleBinding }}
roleRef:
 kind: ClusterRole
 name: {{ .Values.rbac.roleName }}
 apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: ServiceAccount
   name: {{ .Values.serviceAccount.name }}
   namespace: {{ .Values.namespace }}

