apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.tokenSecret.name }}
    namespace: {{ .Values.namespace }}
    annotations:
      kubernetes.io/service-account.name: {{ .Values.serviceAccount.name }}
type: kubernetes.io/service-account-token

